### PR TITLE
fix: rework on handling DOS device paths on Windows

### LINKED ISSUE #65: Mounted Volume in the path causes incorrect resolution output
Minimal repro here: https://github.com/chenxinyanc/unrs-resolver-mounted-partition

When resolving for a module, if there is a mount point instead of ordinary folder within the path of the resolved file, `unrs-resolver` gives incorrect outputs.

I'm reporting this issue because both [eslint-import-resolver-typescript](https://www.npmjs.com/package/eslint-import-resolver-typescript/v/4.3.2?activeTab=dependencies) and [eslint-plugin-import-x](https://www.npmjs.com/package/eslint-plugin-import-x/v/4.10.3?activeTab=dependencies) are using `unrs-resolver`.

Image

For example, suppose there is a [Mounted Volume](https://learn.microsoft.com/en-us/windows/win32/fileio/volume-mount-points) named "mount-root" under current directory, the following code

```js
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ResolverFactory } from "unrs-resolver";

const resolver = new ResolverFactory({
  tsconfig: {
    configFile: 'tsconfig.json',
  },
});
const dir = path.resolve(fileURLToPath(import.meta.url), '..');
// console.log("dir: ", dir);

const resolved = resolver.sync(dir, './mount-root/foo.ts');
console.log(resolved);
```

currently prints something like
```
{
  path: '...\\unrs-resolver-mounted-partition\\src\\Volume{3b0ca266-7f02-4f2c-938c-50931634f3fb}\\foo.ts',
  moduleType: 'module',
  packageJsonPath: '...\\unrs-resolver-mounted-partition\\package.json'
}
```

where "Volume{3b0ca266-7f02-4f2c-938c-50931634f3fb}" is supposed to be "mount-root".

Please refer to the README.md of my reproduction repo attached above for details.

### PR DESCRIPTION
**Pull request by chenxinyanc**
This PR is cherry-picked from the first several iterations of oxc-project/oxc-resolver#455 and fixes #65

> 
> This PR changed the name and return type of `strip_windows_prefix` to `try_strip_windows_prefix`, allowing it to return `None` to indicate unsupported [DOS device paths](https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats#dos-device-paths).
> 
> Most significantly, symlinks referring to a drive without drive letter, usually accessed via a mount point (Mounted Volume), should not be resolved at all, as nodejs `import`/`require` does not support such properly, as of Node 22.
> 
> This PR also rectified the [UNC path](https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats#unc-paths) resolution to prepend the `"\\"` portion to the path.

----

> [!IMPORTANT]
> Improves handling of Windows DOS device paths by updating `strip_windows_prefix` to `try_strip_windows_prefix`, returning `None` for unsupported paths, and updating related functions and tests.
> 
>   - **Behavior**:
>     - Renames `strip_windows_prefix` to `try_strip_windows_prefix` in `windows.rs`, changing return type to `Option<PathBuf>` to return `None` for unsupported DOS device paths.
>     - Updates `try_read_link` in `file_system.rs` and `fs_cache.rs` to handle `None` return value, avoiding symlink resolution for unsupported paths.
>     - Modifies `ResolveOptions` in `options.rs` to document behavior for symlinks pointing to unsupported paths.
>   - **Tests**:
>     - Adds tests in `windows.rs` to verify `try_strip_windows_prefix` returns `None` for unsupported paths and correct paths for supported ones.
>     - Updates `memory_fs.rs` to reflect changes in `try_read_link` behavior.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=unrs%2Funrs-resolver&utm_source=github&utm_medium=referral)<sup> for aa869cae065f21e1fd36028a12ebea6e401a555f. You can [customize](https://app.ellipsis.dev/unrs/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

----

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved handling of Windows-specific symlink targets by not following unsupported or unrepresentable paths, such as volume GUID and certain DOS device paths.
- **Documentation**
	- Clarified symlink resolution behavior on Windows, specifying when symlinks are not followed due to unsupported target paths.
	- Enhanced error documentation for unsupported Windows path prefixes during symlink resolution.

### CODE REVIEW

**Comment by JounQin** [comment]
@chenxinyanc CI/lint is broken.

**Comment by chenxinyanc** [comment]
It seems there is still issue with this PR. It seems `Cache::canonicalize` is not working for my case.

image

I'll hold it off until the `ResolverFactory` works on my side. The challenging part is, it seems we cannot come up with a clean unit test that can mount an NTFS partition to a folder, and then test `ResolverFactory` against it.

**Comment by JounQin** [comment]
I'm going to merge upstream changes now.

**Comment by chenxinyanc** [comment]
> I'm going to merge upstream changes now.

Sure. This PR may take some time. I've discovered something tough and am still debugging through it.

Anyway, this would still be a rare & wonderful experience for me even if this PR cannot be merged in the end (conflicts incoming!).

----

btw should the package-level import for [the following package.json](https://app.unpkg.com/@fluentui/react-components@9.62.0/files/package.json) be accepted by the resolver?

```jsonc
{
  "name": "@fluentui/react-components",
  "version": "9.62.0",
  "main": "lib-commonjs/index.js",
  "module": "lib/index.js",
  "typings": "./dist/index.d.ts",
  "sideEffects": false,
  // ...
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "node": "./lib-commonjs/index.js",
      "import": "./lib/index.js",
      "require": "./lib-commonjs/index.js"
      // there is no "default" here.
    },
    "./package.json": "./package.json",
    "./unstable": {
      "types": "./dist/unstable.d.ts",
      "node": "./lib-commonjs/unstable/index.js",
      "import": "./lib/unstable/index.js",
      "require": "./lib-commonjs/unstable/index.js"
    }
  },
}
```

I'm asking because when I tried to resolve its entry point with

```rust
resolver.resolve(&fixture, "@fluentui/react-components").map(|r| r.full_path())
```

I saw the following `Err` returned from `resolve`

```
Err(PackagePathNotExported(".", "<...>\\node_modules\\@fluentui\\react-components\\package.json"))
```

... and it seems `unrs-resolver` and `oxc-resolver` (upstream) are expecting `"default"` field inside `$.exports.["."]`.

https://github.com/oxc-project/oxc-resolver/blob/5fc3395ea5ffa102a756dfc01ea5181e4765af11/src/lib.rs#L1684-L1689

**Comment by JounQin** [comment]
> Sure. This PR may take some time. I've discovered something tough (see below) and am still debugging through it.

So you mean the upstream merged PR won't resolve your original issue, right?

> btw should the package-level import for [the following package.json](https://app.unpkg.com/@fluentui/react-components@9.62.0/files/package.json) be accepted by the resolver?

You need to pass the custom `conditionNames` option.

**Comment by chenxinyanc** [comment]
> > btw should the package-level import for [the following package.json](https://app.unpkg.com/@fluentui/react-components@9.62.0/files/package.json) be accepted by the resolver?
> 
> You need to pass the custom `conditionNames` option, the default value is `[]`.

Thanks! Then my change here is basically done. I've tried the change locally with `eslint-plugin-import-x` --> `eslint-plugin-typescript` and it works as if the Volume mount point `node_modules` were an ordinary folder. You (or somebody else) could probably also give it a try if you happen to have Windows environment set up.

image

And I'll give it a check whether it's possible to write unit test for this PR. While it's not trivial to set up a Mounted Volume in CI pipeline, I can test whether we can just set up some plain symlinks pointing to a DOS device path (something starting with `//?/...`).

> > Sure. This PR may take some time. I've discovered something tough (see below) and am still debugging through it.
> 
> So you mean the upstream merged PR won't resolve your original issue, right?
> 

I thought Boshen is using a completely different approach in oxc-project/oxc-resolver#455. Let me give that change a try before reaching back.

**Comment by chenxinyanc** [comment]
OK it turns out Boshen has reverted the change with `dunce::simplified`, so I guess I'll carry on 😂

However, there is [bug with my prior change](https://github.com/unrs/unrs-resolver/pull/84#issuecomment-2818273456) made in oxc-project/oxc-resolver#455 , so I'll propose another PR to cherry-pick the change back to the upstream, once we have settled the PR here.

**Comment by JounQin** [comment]
Let me do a merge-upstream first before you can get the diffs/conflicts confidently.

**Comment by chenxinyanc** [comment]
> Let me do a merge-upstream first before you can get the diffs/conflicts confidently.

Thanks! I'll resolve the conflict.

And I propose that
* we keep this PR a draft PR, and
* when I'm done with conflict resolution and unit tests in this PR, I open a PR in `oxc-resolver` with the same change, and
* after the PR gets accepted in `oxc-resolver`, you just need to do a simple merge-upstream, and
* eventually, we close this PR in `unrs-resolver` without needing to merge it.

Sorry for the troubles 🌚 things should have been simpler if I had stuck to making changes in `oxc-resolver` repo instead.

**Comment by JounQin** [comment]
> Sorry for the troubles 🌚 things should have been simpler if I had stuck to making changes in oxc-resolver repo instead.

Ah, that was me proposed to change first at here, but I still think that's a better approach personally, feel free to disagree and do things on your own way.

**Comment by JounQin** [comment]
CI is all green now.

**Comment by JounQin** [comment]
@coderabbitai full review

**Comment by JounQin** [comment]
Friendly ping @chenxinyanc, please help to confirm that is there anything I missed, so that I'll merge this PR as-is ASAP.

**Comment by JounQin** [comment]
@coderabbitai full review

**Comment by chenxinyanc** [comment]
> I've done the rebase for you. @chenxinyanc

@JounQin Thanks for the follow-up. I'm afraid I'll have to force push here, as I've already resolved conflict yesterday and waited for the update in the main branch.

I'm following the idea from Boshen in `oxc-resolver` and replacing all the `io::Result<Option<PathBuf>>` with `Result<PathBuf, ResolveError>` in my latest iteration. Consider this iteration as final.

I've also tried with creating symlinks in unit tests, but it's not trivial, and I might need to query for the Volume ID with Win 32 API. Even if it were possible, it won't be in this PR. So, again, consider this iteration as final one.

**Comment by JounQin** [comment]
@chenxinyanc That's totally fine and greater actually, but this CI is broken again now. :(

File: src/windows.rs [hunk 1]
```diff
@@ -4,16 +4,18 @@ use crate::ResolveError;
 
 /// When applicable, converts a [DOS device path](https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats#dos-device-paths)
 /// to a normal path (usually, "Traditional DOS paths" or "UNC path") that can be consumed by the `import`/`require` syntax of Node.js.
-/// Returns `None` if the path cannot be represented as a normal path.
-pub fn try_strip_windows_prefix(path: PathBuf) -> Result<PathBuf, ResolveError> {
+///
+/// # Errors
+/// Returns error of [`ResolveError::PathNotSupported`] kind if the path cannot be represented as a normal path.
+pub fn strip_windows_prefix(path: PathBuf) -> Result<PathBuf, ResolveError> {
```
Comment (JounQin) [inline src/windows.rs:10]: Is the renaming intented?

Comment (chenxinyanc) [reply src/windows.rs:10]: Yes. It's named `strip_windows_prefix` before my changes. I've renamed it into `try_strip_windows_prefix` in prior changes as the function has been changed to return `Option<PathBuf>`.

Now considering this function can return `Err(ResolveError)`, I'm restoring the function name in this PR.

----

I was following a traditional rule mentioned here: https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/exceptions-and-performance#try-parse-pattern

> ✔️ DO use the prefix "Try" and Boolean return type for methods implementing this (Try-Parse Pattern) pattern.

I'm taking `Err` in Rust the same position as `Exception` in other languages.

File: src/file_system.rs [hunk 2]
```diff
@@ -186,17 +192,13 @@ impl FileSystemOs {
...
             if #[cfg(target_os = "windows")] {
-                match crate::windows::try_strip_windows_prefix(path) {
-                    // We won't follow the link if we cannot represent its target properly.
-                    Ok(p) | Err(crate::ResolveError::PathNotSupported(p)) => Ok(p),
-                    _ => unreachable!(),
-                }
+                crate::windows::strip_windows_prefix(path)
             } else {
-                Ok(path)
+                Ok(path.to_path_buf())
```
Comment (JounQin) [inline src/file_system.rs:201]:
```suggestion
                Ok(path)
```

**Review by JounQin — CHANGES_REQUESTED** [review]

File: src/tests/memory_fs.rs [hunk 3]
```diff
@@ -72,8 +72,8 @@ impl FileSystem for MemoryFS {
         self.metadata(path)
     }
 
-    fn read_link(&self, _path: &Path) -> io::Result<PathBuf> {
-        Err(io::Error::new(io::ErrorKind::NotFound, "not a symlink"))
+    fn read_link(&self, _path: &Path) -> Result<PathBuf, ResolveError> {
+        Err(io::Error::new(io::ErrorKind::NotFound, "not a symlink").into())
```
Comment (JounQin) [inline src/tests/memory_fs.rs:76]:
```suggestion
        Err(Error::new(ErrorKind::NotFound, "not a symlink").into())
```

Let's be consistent.

**Review by JounQin — CHANGES_REQUESTED** [review]

File: src/file_system.rs (hunk 2 above)
Comment (chenxinyanc) [reply src/file_system.rs]: Updated.

File: src/tests/memory_fs.rs (hunk 3 above)
Comment (chenxinyanc) [reply src/tests/memory_fs.rs:76]: Which `Error` did you mean? L76 means

```rust
Err(ResolveError::from(io::Error::new(io::ErrorKind::NotFound, "not a symlink")))
```

Simply removing `io::` prefix will lead to error.

**Comment by chenxinyanc** [comment]
I'm not sure how to resolve [the last CI failure](https://github.com/unrs/unrs-resolver/pull/84/checks?check_run_id=40997971270).

**Review by JounQin — APPROVED** [review]
Thanks for your efforts! I think it's ready to be merged, WDYT? @chenxinyanc

**Comment by JounQin** [comment]
> I'm not sure how to resolve [the last CI failure](https://github.com/unrs/unrs-resolver/pull/84/checks?check_run_id=40997971270).

It's some kind of coding style issue form @codacy, I've bypassed that check, let's not waste time on it.

**Comment by chenxinyanc** [comment]
> Thanks for your efforts! I think it's ready to be merged, WDYT? @chenxinyanc

LGTM

I'll follow up with a PR of for the test case later.

**Comment by JounQin** [comment]
> I'll follow up with another PR for the test case later.

Which test case do you mean? I thought all cases were covered already, but it's also fine to merge this PR as-is first.

**Comment by chenxinyanc** [comment]
> it's also fine to merge this PR as-is first.

Yes please.

> Which test case do you mean?

I meant adding a new test case to cover the behavior that "we won't follow symlinks if they are pointing to a DOS device path with Volume GUID (`\\.\Volume{...}\`)". However, it may take some time for me to propose that PR. See https://github.com/unrs/unrs-resolver/pull/84#issuecomment-2823118621.
